# ***Importing the datasets:***

In [4]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',100)


from google.colab import files
upload = files.upload("matches.csv")
uploaded1 = files.upload("deliveries.csv")

Saving deliveries.csv to deliveries.csv/deliveries.csv

# ***Reading data from the files:***

In [6]:
matches = pd.read_csv("/content/matches.csv/matches.csv")
deliveries = pd.read_csv("/content/deliveries.csv/deliveries.csv")

        match_id  inning         batting_team                 bowling_team  \
0              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
1              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
2              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
3              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
4              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
...          ...     ...                  ...                          ...
179073     11415       2  Chennai Super Kings               Mumbai Indians
179074     11415       2  Chennai Super Kings               Mumbai Indians
179075     11415       2  Chennai Super Kings               Mumbai Indians
179076     11415       2  Chennai Super Kings               Mumbai Indians
179077     11415       2  Chennai Super Kings               Mumbai Indians

        over  ball    batsman non_striker      bowler  is_super_over  \
0          1     1  DA Warner    S Dhawan    TS Mills              0
1          1     2  DA Warner    S Dhawan    TS Mills              0
2          1     3  DA Warner    S Dhawan    TS Mills              0
3          1     4  DA Warner    S Dhawan    TS Mills              0
4          1     5  DA Warner    S Dhawan    TS Mills              0
...      ...   ...        ...         ...         ...            ...
179073    20     2  RA Jadeja   SR Watson  SL Malinga              0
179074    20     3  SR Watson   RA Jadeja  SL Malinga              0
179075    20     4  SR Watson   RA Jadeja  SL Malinga              0
179076    20     5  SN Thakur   RA Jadeja  SL Malinga              0
179077    20     6  SN Thakur   RA Jadeja  SL Malinga              0

        wide_runs  bye_runs  legbye_runs  noball_runs  penalty_runs  \
0               0         0            0            0             0
1               0         0            0            0             0
2               0         0            0            0             0
3               0         0            0            0             0
4               2         0            0            0             0
...           ...       ...          ...          ...           ...
179073          0         0            0            0             0
179074          0         0            0            0             0
179075          0         0            0            0             0
179076          0         0            0            0             0
179077          0         0            0            0             0

        batsman_runs  extra_runs  total_runs player_dismissed dismissal_kind  \
0                  0           0           0              NaN            NaN
1                  0           0           0              NaN            NaN
2                  4           0           4              NaN            NaN
3                  0           0           0              NaN            NaN
4                  0           2           2              NaN            NaN
...              ...         ...         ...              ...            ...
179073             1           0           1              NaN            NaN
179074             2           0           2              NaN            NaN
179075             1           0           1        SR Watson        run out
179076             2           0           2              NaN            NaN
179077             0           0           0        SN Thakur            lbw

          fielder
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
179073        NaN
179074        NaN
179075  KH Pandya
179076        NaN
179077        NaN

[179078 rows x 21 columns]

# ***Merged Both CSV's***

In [12]:
combined = pd.merge(deliveries,matches,left_on="match_id",right_on="id")
print(combined)

        match_id  inning         batting_team                 bowling_team  \
0              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
1              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
2              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
3              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
4              1       1  Sunrisers Hyderabad  Royal Challengers Bangalore
...          ...     ...                  ...                          ...
179073     11415       2  Chennai Super Kings               Mumbai Indians
179074     11415       2  Chennai Super Kings               Mumbai Indians
179075     11415       2  Chennai Super Kings               Mumbai Indians
179076     11415       2  Chennai Super Kings               Mumbai Indians
179077     11415       2  Chennai Super Kings               Mumbai Indians

        over  ball    batsman non_striker      bowler  is_super_over  \
0          1     1  DA Warner    S Dhawan    TS Mills              0
1          1     2  DA Warner    S Dhawan    TS Mills              0
2          1     3  DA Warner    S Dhawan    TS Mills              0
3          1     4  DA Warner    S Dhawan    TS Mills              0
4          1     5  DA Warner    S Dhawan    TS Mills              0
...      ...   ...        ...         ...         ...            ...
179073    20     2  RA Jadeja   SR Watson  SL Malinga              0
179074    20     3  SR Watson   RA Jadeja  SL Malinga              0
179075    20     4  SR Watson   RA Jadeja  SL Malinga              0
179076    20     5  SN Thakur   RA Jadeja  SL Malinga              0
179077    20     6  SN Thakur   RA Jadeja  SL Malinga              0

        wide_runs  bye_runs  legbye_runs  noball_runs  penalty_runs  \
0               0         0            0            0             0
1               0         0            0            0             0
2               0         0            0            0             0
3               0         0            0            0             0
4               2         0            0            0             0
...           ...       ...          ...          ...           ...
179073          0         0            0            0             0
179074          0         0            0            0             0
179075          0         0            0            0             0
179076          0         0            0            0             0
179077          0         0            0            0             0

        batsman_runs  extra_runs  total_runs player_dismissed dismissal_kind  \
0                  0           0           0              NaN            NaN
1                  0           0           0              NaN            NaN
2                  4           0           4              NaN            NaN
3                  0           0           0              NaN            NaN
4                  0           2           2              NaN            NaN
...              ...         ...         ...              ...            ...
179073             1           0           1              NaN            NaN
179074             2           0           2              NaN            NaN
179075             1           0           1        SR Watson        run out
179076             2           0           2              NaN            NaN
179077             0           0           0        SN Thakur            lbw

          fielder     id  season       city        date                team1  \
0             NaN      1    2017  Hyderabad  2017-04-05  Sunrisers Hyderabad
1             NaN      1    2017  Hyderabad  2017-04-05  Sunrisers Hyderabad
2             NaN      1    2017  Hyderabad  2017-04-05  Sunrisers Hyderabad
3             NaN      1    2017  Hyderabad  2017-04-05  Sunrisers Hyderabad
4             NaN      1    2017  Hyderabad  2017-04-05  Sunrisers Hyderabad
...           ...    ...     ...        ...         ...                  ...
179073        NaN  11415    2019  Hyderabad    12/05/19       Mumbai Indians
179074        NaN  11415    2019  Hyderabad    12/05/19       Mumbai Indians
179075  KH Pandya  11415    2019  Hyderabad    12/05/19       Mumbai Indians
179076        NaN  11415    2019  Hyderabad    12/05/19       Mumbai Indians
179077        NaN  11415    2019  Hyderabad    12/05/19       Mumbai Indians

                              team2                  toss_winner  \
0       Royal Challengers Bangalore  Royal Challengers Bangalore
1       Royal Challengers Bangalore  Royal Challengers Bangalore
2       Royal Challengers Bangalore  Royal Challengers Bangalore
3       Royal Challengers Bangalore  Royal Challengers Bangalore
4       Royal Challengers Bangalore  Royal Challengers Bangalore
...                             ...                          ...
179073          Chennai Super Kings               Mumbai Indians
179074          Chennai Super Kings               Mumbai Indians
179075          Chennai Super Kings               Mumbai Indians
179076          Chennai Super Kings               Mumbai Indians
179077          Chennai Super Kings               Mumbai Indians

       toss_decision  result  dl_applied               winner  win_by_runs  \
0              field  normal           0  Sunrisers Hyderabad           35
1              field  normal           0  Sunrisers Hyderabad           35
2              field  normal           0  Sunrisers Hyderabad           35
3              field  normal           0  Sunrisers Hyderabad           35
4              field  normal           0  Sunrisers Hyderabad           35
...              ...     ...         ...                  ...          ...
179073           bat  normal           0       Mumbai Indians            1
179074           bat  normal           0       Mumbai Indians            1
179075           bat  normal           0       Mumbai Indians            1
179076           bat  normal           0       Mumbai Indians            1
179077           bat  normal           0       Mumbai Indians            1

        win_by_wickets player_of_match  \
0                    0    Yuvraj Singh
1                    0    Yuvraj Singh
2                    0    Yuvraj Singh
3                    0    Yuvraj Singh
4                    0    Yuvraj Singh
...                ...             ...
179073               0       JJ Bumrah
179074               0       JJ Bumrah
179075               0       JJ Bumrah
179076               0       JJ Bumrah
179077               0       JJ Bumrah

                                            venue      umpire1    umpire2  \
0       Rajiv Gandhi International Stadium, Uppal  AY Dandekar   NJ Llong
1       Rajiv Gandhi International Stadium, Uppal  AY Dandekar   NJ Llong
2       Rajiv Gandhi International Stadium, Uppal  AY Dandekar   NJ Llong
3       Rajiv Gandhi International Stadium, Uppal  AY Dandekar   NJ Llong
4       Rajiv Gandhi International Stadium, Uppal  AY Dandekar   NJ Llong
...                                           ...          ...        ...
179073         Rajiv Gandhi Intl. Cricket Stadium  Nitin Menon  Ian Gould
179074         Rajiv Gandhi Intl. Cricket Stadium  Nitin Menon  Ian Gould
179075         Rajiv Gandhi Intl. Cricket Stadium  Nitin Menon  Ian Gould
179076         Rajiv Gandhi Intl. Cricket Stadium  Nitin Menon  Ian Gould
179077         Rajiv Gandhi Intl. Cricket Stadium  Nitin Menon  Ian Gould

            umpire3
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
179073  Nigel Llong
179074  Nigel Llong
179075  Nigel Llong
179076  Nigel Llong
179077  Nigel Llong

[179078 rows x 39 columns]

# ***Overviewing every columns in the dataset:***

In [13]:
combined.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date', 'team1',
       'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied',
       'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue',
       'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

# ***Calulating the total rows x columns:***

In [ ]:
combined.shape

(179078, 39)

# ***Overviewing the data of first 5 rows of the dataset:***

In [14]:
combined.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,2,0,0,0,0,0,2,2,NaN,NaN,NaN,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

# ***Overviewing the data for last 5 rows of the dataset:***

In [28]:
combined.tail()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,0,0,0,SN Thakur,lbw,NaN,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

# ***Extracting info of all the columns with their non-null count & dtype for each:***

In [25]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 39 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
 21  id                179078 non-null  int64
 22  season            179078 non-null  int64
 23  city              177378 non-null  object
 24  date              179078 non-null  object
 25  team1             179078 non-null  object
 26  team2             179078 non-null  object
 27  toss_winner       179078 non-null  object
 28  toss_decision     179078 non-null  object
 29  result            179078 non-null  object
 30  dl_applied        179078 non-null  int64
 31  winner            178706 non-null  object
 32  win_by_runs       179078 non-null  int64
 33  win_by_wickets    179078 non-null  int64
 34  player_of_match   178706 non-null  object
 35  venue             179078 non-null  object
 36  umpire1           178578 non-null  object
 37  umpire2           178578 non-null  object
 38  umpire3           28366 non-null   object
dtypes: int64(18), object(21)
memory usage: 53.3+ MB

# ***Extracting the Statistical Data for certain columns:***

In [26]:
combined.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,id,season,dl_applied,win_by_runs,win_by_wickets
count,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000
mean,1802.252957,1.482952,10.162488,3.615587,0.000452,0.036721,0.004936,0.021136,0.004183,0.000056,1.246864,0.067032,1.313897,1802.252957,2013.444510,0.017914,13.404036,3.261579
std,3472.322805,0.502074,5.677684,1.806966,0.021263,0.251161,0.116480,0.194908,0.070492,0.016709,1.608270,0.342553,1.605422,3472.322805,3.363947,0.132639,23.261007,3.347033
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2008.000000,0.000000,0.000000,0.000000
25%,190.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,190.000000,2011.000000,0.000000,0.000000,0.000000
50%,379.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,379.000000,2013.000000,0.000000,0.000000,3.000000
75%,567.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,567.000000,2016.000000,0.000000,19.000000,6.000000
max,11415.000000,5.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,7.000000,7.000000,10.000000,11415.000000,2019.000000,1.000000,146.000000,10.000000

# ***Returning the type of data stored in each column:***

In [27]:
combined.dtypes

match_id             int64
inning               int64
batting_team        object
bowling_team        object
over                 int64
ball                 int64
batsman             object
non_striker         object
bowler              object
is_super_over        int64
wide_runs            int64
bye_runs             int64
legbye_runs          int64
noball_runs          int64
penalty_runs         int64
batsman_runs         int64
extra_runs           int64
total_runs           int64
player_dismissed    object
dismissal_kind      object
fielder             object
id                   int64
season               int64
city                object
date                object
team1               object
team2               object
toss_winner         object
toss_decision       object
result              object
dl_applied           int64
winner              object
win_by_runs          int64
win_by_wickets       int64
player_of_match     object
venue               object
umpire1             object
umpire2             object
umpire3             object
dtype: object

# ***Extracts the sum of all the null values for each individual columns:***

In [17]:
combined.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
id                       0
season                   0
city                  1700
date                     0
team1                    0
team2                    0
toss_winner              0
toss_decision            0
result                   0
dl_applied               0
winner                 372
win_by_runs              0
win_by_wickets           0
player_of_match        372
venue                    0
umpire1                500
umpire2                500
umpire3             150712
dtype: int64

# ***Counting total number of unqiue values in the columns:***

In [18]:
combined.nunique()

match_id            756
inning                5
batting_team         15
bowling_team         15
over                 20
ball                  9
batsman             516
non_striker         511
bowler              405
is_super_over         2
wide_runs             6
bye_runs              5
legbye_runs           6
noball_runs           5
penalty_runs          2
batsman_runs          8
extra_runs            7
total_runs           10
player_dismissed    487
dismissal_kind        9
fielder             499
id                  756
season               12
city                 32
date                546
team1                15
team2                15
toss_winner          15
toss_decision         2
result                3
dl_applied            2
winner               15
win_by_runs          89
win_by_wickets       11
player_of_match     226
venue                41
umpire1              61
umpire2              65
umpire3              25
dtype: int64

# ***Displaying the random data of any 5 rows:***

In [24]:
combined.sample(5)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
72015,306,1,Royal Challengers Bangalore,Mumbai Indians,7,4,CH Gayle,MA Agarwal,MM Patel,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,306,2011,Chennai,2011-05-27,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Royal Challengers Bangalore,43,0,CH Gayle,"MA Chidambaram Stadium, Chepauk",Asad Rauf,SJA Taufel,NaN
30502,131,2,Deccan Chargers,Chennai Super Kings,15,6,DR Smith,HH Gibbs,JDP Oram,0,0,0,0,0,0,6,0,6,NaN,NaN,NaN,131,2009,Durban,2009-04-27,Chennai Super Kings,Deccan Chargers,Deccan Chargers,field,normal,0,Deccan Chargers,0,6,HH Gibbs,Kingsmead,IL Howell,TH Wijewardene,NaN
94475,399,2,Chennai Super Kings,Pune Warriors,3,7,SK Raina,M Vijay,B Kumar,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,399,2013,Chennai,2013-04-15,Pune Warriors,Chennai Super Kings,Pune Warriors,bat,normal,0,Pune Warriors,24,0,SPD Smith,"MA Chidambaram Stadium, Chepauk",Asad Rauf,AK Chaudhary,NaN
2696,12,1,Royal Challengers Bangalore,Mumbai Indians,18,3,KM Jadhav,P Negi,JJ Bumrah,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN,12,2017,Bangalore,2017-04-14,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,KA Pollard,M Chinnaswamy Stadium,KN Ananthapadmanabhan,AK Chaudhary,NaN
23301,101,1,Rajasthan Royals,Royal Challengers Bangalore,1,7,SA Asnodkar,GC Smith,Z Khan,0,0,0,0,0,0,6,0,6,NaN,NaN,NaN,101,2008,Jaipur,2008-05-17,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Rajasthan Royals,65,0,GC Smith,Sawai Mansingh Stadium,BF Bowden,SL Shastri,NaN

# ***Calculating the total number of overs bowled :***

In [23]:
combined.value_counts("over").sum()

np.int64(179078)

# ***Extra commands for EDA:***

In [7]:
#matches.shape
deliveries.shape

(179078, 21)

In [8]:
#matches.head()
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,2,0,0,0,0,0,2,2,NaN,NaN,NaN

In [9]:
matches.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [10]:
deliveries.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [11]:
matches["season"].value_counts()

season
2013    76
2012    74
2011    73
2010    60
2016    60
2018    60
2019    60
2014    60
2017    59
2015    59
2008    58
2009    57
Name: count, dtype: int64

In [ ]:
matches.groupby("winner")["id"].count().sort_values(ascending=False)

winner
Mumbai Indians                 109
Chennai Super Kings            100
Kolkata Knight Riders           92
Royal Challengers Bangalore     84
Kings XI Punjab                 82
Rajasthan Royals                75
Delhi Daredevils                67
Sunrisers Hyderabad             58
Deccan Chargers                 29
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Delhi Capitals                  10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: id, dtype: int64

In [ ]:
combined[combined["batsman_runs"] == 6].groupby("season")["batsman_runs"].count()

season
2008    623
2009    508
2010    587
2011    639
2012    733
2013    681
2014    715
2015    692
2016    639
2017    706
2018    869
2019    778
Name: batsman_runs, dtype: int64